window.ESAVocabularyBank=[
{w:"assist",level:"A2",category:"customer-service",meaning:"help someone",hinglish:"Kisi ki help karna."},
{w:"confirm",level:"A2",category:"workplace",meaning:"check and say something is correct",hinglish:"Kisi cheez ko check karke sure karna."},
{w:"complaint",level:"B1",category:"customer-service",meaning:"a statement that something is wrong",hinglish:"Customer ki problem ya dissatisfaction ki statement."},
{w:"courteous",level:"B1",category:"customer-service",meaning:"polite and respectful",hinglish:"Respectful aur polite."},
{w:"efficient",level:"B1",category:"workplace",meaning:"working well without unnecessary waste",hinglish:"Kam time aur resources mein achhe se kaam karna."},
{w:"escalate",level:"B2",category:"customer-service",meaning:"pass a serious issue to a higher level",hinglish:"Serious problem ko higher level par bhejna."},
{w:"fluent",level:"B1",category:"speaking",meaning:"able to communicate smoothly",hinglish:"Language ko smoothly bol pana."},
{w:"genuine",level:"B1",category:"customer-service",meaning:"real and sincere",hinglish:"Asli aur sincere."},
{w:"handle",level:"B1",category:"workplace",meaning:"deal with something successfully",hinglish:"Kisi situation ya person ko manage karna."},
{w:"maintain",level:"B1",category:"workplace",meaning:"keep something working or continuing well",hinglish:"Kisi cheez ko achhi condition ya level par rakhna."},
{w:"negotiate",level:"B2",category:"workplace",meaning:"discuss to find an agreement",hinglish:"Baat-cheet karke agreement tak pahunchna."},
{w:"priority",level:"B1",category:"workplace",meaning:"something that must be dealt with first",hinglish:"Jo kaam sabse important ho aur pehle karna ho."},
{w:"punctual",level:"A2",category:"workplace",meaning:"arriving at the expected time",hinglish:"Time par hona."},
{w:"respond",level:"A2",category:"speaking",meaning:"reply or react to something",hinglish:"Kisi baat ka reply ya reaction dena."},
{w:"responsible",level:"B1",category:"workplace",meaning:"reliable and trusted with a duty",hinglish:"Kisi duty ki responsibility lena aur reliable rehna."},
{w:"schedule",level:"B1",category:"aviation",meaning:"a planned timetable",hinglish:"Planned timetable ya time plan."},
{w:"solution",level:"B1",category:"workplace",meaning:"a way to solve a problem",hinglish:"Problem ka practical answer."},
{w:"sufficient",level:"B2",category:"workplace",meaning:"enough for what is needed",hinglish:"Jitna required ho, utna enough."},
{w:"temporary",level:"B1",category:"workplace",meaning:"not permanent",hinglish:"Sirf limited time ke liye."},
{w:"verify",level:"B1",category:"aviation",meaning:"check carefully",hinglish:"Carefully check karke sure karna."},
{w:"attitude",level:"B1",category:"interview",meaning:"your way of thinking or behaving",hinglish:"Kisi situation ke towards aapka mindset ya behaviour."},
{w:"cooperate",level:"B1",category:"workplace",meaning:"work together",hinglish:"Milkar kaam karna."},
{w:"courtesy",level:"B2",category:"customer-service",meaning:"polite and respectful behaviour",hinglish:"Respect dikhane wala polite behaviour."},
{w:"departure",level:"B1",category:"aviation",meaning:"the act or time of leaving",hinglish:"Kisi jagah se nikalne ka act ya time."},
{w:"destination",level:"B1",category:"aviation",meaning:"the place you are going to",hinglish:"Jahan aap travel karke jaana chahte hain."},
{w:"emergency",level:"B1",category:"aviation",meaning:"a serious situation needing quick action",hinglish:"Achanak serious situation jismein turant action zaroori ho."},
{w:"reliable",level:"B1",category:"interview",meaning:"someone or something you can trust",hinglish:"Jis par bharosa kiya ja sake."},
{w:"professional",level:"B1",category:"interview",meaning:"skilled and suitable for the workplace",hinglish:"Workplace ke liye skilled aur proper behaviour wala."},
{w:"confident",level:"B1",category:"interview",meaning:"feeling sure of yourself",hinglish:"Apni ability par bharosa hona."},
{w:"resolve",level:"B1",category:"customer-service",meaning:"solve a problem",hinglish:"Problem ko solve karna."},
{w:"feedback",level:"B1",category:"interview",meaning:"information about what went well and what to improve",hinglish:"Kya achha hua aur kya improve karna hai, uski comments."},
{w:"accommodate",level:"B2",category:"customer-service",meaning:"adjust something to meet someone's needs",hinglish:"Kisi ki need ke according arrangement karna."},
{w:"assistance",level:"B1",category:"customer-service",meaning:"help or support given to someone",hinglish:"Kisi ko di gayi help ya support."},
{w:"baggage",level:"B1",category:"aviation",meaning:"bags and personal items taken on a journey",hinglish:"Travel ke waqt saath le jaane wale bags."},
{w:"boarding",level:"B1",category:"aviation",meaning:"the process of getting onto a plane or other vehicle",hinglish:"Plane ya vehicle mein chadhne ka process."},
{w:"delay",level:"A2",category:"aviation",meaning:"a situation in which something happens later than planned",hinglish:"Kisi cheez ka planned time se late hona."},
{w:"professionalism",level:"B2",category:"interview",meaning:"the skills, behaviour and standards expected in a profession",hinglish:"Professional kaam aur behaviour ke required standards."},
{w:"adapt",level:"B1",category:"interview",meaning:"change your approach to fit a new situation",hinglish:"Nayi situation ke according apna tareeka change karna."},
{w:"achieve",level:"B1",category:"interview",meaning:"succeed in reaching a goal",hinglish:"Mehnat karke goal hasil karna."},
{w:"accurate",level:"B1",category:"aviation",meaning:"correct and free from important mistakes",hinglish:"Bilkul sahi aur important galti ke bina."},
{w:"alert",level:"B1",category:"aviation",meaning:"awake and paying close attention",hinglish:"Sajag rehna aur poora dhyan dena."},
{w:"approach",level:"B1",category:"aviation",meaning:"a way of dealing with something; also moving closer",hinglish:"Problem ko ek tareeke se handle karna ya paas aana."},
{w:"assure",level:"B2",category:"customer-service",meaning:"tell someone confidently that something is true",hinglish:"Kisi ko confidence dena ki sab theek hai."},
{w:"communicate",level:"B1",category:"speaking",meaning:"share information, ideas or feelings",hinglish:"Information ya ideas ko clearly share karna."},
{w:"eligible",level:"B1",category:"interview",meaning:"having the necessary conditions or qualifications",hinglish:"Required conditions ya qualification hona."},
{w:"flexible",level:"B1",category:"workplace",meaning:"able to adapt easily to change",hinglish:"Situation change hone par easily adjust kar pana."},
{w:"objective",level:"B2",category:"interview",meaning:"a goal or result you want to achieve",hinglish:"Woh goal jo aap achieve karna chahte hain."},
{w:"initiative",level:"B2",category:"workplace",meaning:"the ability to act without waiting to be told what to do",hinglish:"Bina baar-baar instruction ka wait kiye action lena."},
{w:"leadership",level:"B2",category:"interview",meaning:"the ability to guide or influence a team",hinglish:"Team ko guide aur influence karne ki ability."},
{w:"collaborate",level:"B2",category:"workplace",meaning:"work jointly with others",hinglish:"Dusron ke saath milkar kaam karna."},
{w:"deadline",level:"B1",category:"workplace",meaning:"the latest time by which something must be completed",hinglish:"Kaam complete karne ki final time limit."},
{w:"procedure",level:"B1",category:"aviation",meaning:"an official or usual way of doing something",hinglish:"Kisi kaam ko karne ka official ya standard tareeka."},
{w:"policy",level:"B1",category:"workplace",meaning:"an official rule or plan used by an organization",hinglish:"Organization ka official rule ya guideline."},
{w:"priority",level:"B1",category:"customer-service",meaning:"something treated as more important than other things",hinglish:"Jo cheez baaki cheezon se zyada important ho."},
{w:"courtesy",level:"B2",category:"aviation",meaning:"polite behaviour that shows respect",hinglish:"Respect show karne wala polite behaviour."},
{w:"passenger",level:"A2",category:"aviation",meaning:"a person travelling in a vehicle but not operating it",hinglish:"Jo person vehicle mein travel karta hai, operate nahi karta."},
{w:"gate",level:"A2",category:"aviation",meaning:"the place at an airport where passengers board a flight",hinglish:"Airport par jahan se passengers flight board karte hain."},
{w:"itinerary",level:"B2",category:"aviation",meaning:"a plan showing the places and times of a journey",hinglish:"Journey ka detailed plan."},
{w:"reservation",level:"B1",category:"customer-service",meaning:"an arrangement to keep a seat, room or service for someone",hinglish:"Seat, room ya service ko pehle se book karke rakhna."},
{w:"refund",level:"B1",category:"customer-service",meaning:"money returned because something was cancelled or unsatisfactory",hinglish:"Cancel ya problem ki wajah se wapas milne wala paisa."},
{w:"courteous",level:"B1",category:"speaking",meaning:"polite and respectful in manner",hinglish:"Baat karne ka respectful aur polite tareeka."},
{w:"clarify",level:"B1",category:"speaking",meaning:"make something easier to understand",hinglish:"Confusion door karke baat ko clear karna."},
{w:"persuade",level:"B2",category:"speaking",meaning:"make someone agree to do or believe something",hinglish:"Kisi ko agree karne ke liye convince karna."},
{w:"empathy",level:"B2",category:"customer-service",meaning:"the ability to understand another person's feelings",hinglish:"Dusre person ki feelings ko samajhne ki ability."},
{w:"patience",level:"B1",category:"customer-service",meaning:"the ability to stay calm while waiting or dealing with difficulty",hinglish:"Difficult situation mein calm rehne ki ability."},
{w:"urgent",level:"B1",category:"aviation",meaning:"needing immediate attention or action",hinglish:"Jisko turant attention ya action chahiye."}
];